### ISSUE TITLE
Finalise infinite scroll

### ISSUE THREAD

**Issue by lolPants** [lolPants/beatsaver-reloaded#24]
## To-do
- [ ] Implement storing beatmaps in redux store
  - [x] Per-route
  - [ ] Refactor to reference a global store
- [ ] Scroll handler
  - [x] Save key to URL on scroll
  - [x] Restore scroll position on navigate
  - [ ] Reset scroll position on PUSH
  - [ ] Fix bugs with search
